# Generated by Django 5.2.17 on 2026-10-08 18:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_digest', models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator('\\A[0-9a-f]{64}\\Z', 'Digest must be 64 lowercase hexadecimal characters.')])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='email_verification_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='accounts_token_user_created')],
                'constraints': [models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('created_at'))), name='accounts_token_expiry_after_creation'), models.CheckConstraint(condition=models.Q(('consumed_at__isnull', True), ('revoked_at__isnull', True), _connector='OR'), name='accounts_token_not_used_and_revoked'), models.UniqueConstraint(condition=models.Q(('consumed_at__isnull', True), ('revoked_at__isnull', True)), fields=('user',), name='accounts_token_one_outstanding')],
            },
        ),
    ]
