# Generated by Django 5.2.17 on 2026-10-08 22:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailverificationtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthConnectionAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state_digest', models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator('\\A[0-9a-f]{64}\\Z', 'Digest must be 64 lowercase hexadecimal characters.')])),
                ('session_digest', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('\\A[0-9a-f]{64}\\Z', 'Digest must be 64 lowercase hexadecimal characters.')])),
                ('client_id', models.CharField(max_length=512)),
                ('expected_generation', models.UUIDField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('claimed_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('superseded_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oauth_connection_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='accounts_oauth_user_created')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('claimed_at__isnull', True), ('superseded_at__isnull', True)), fields=('user',), name='accounts_oauth_one_pending'), models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('created_at'))), name='accounts_oauth_expiry_after'), models.CheckConstraint(condition=models.Q(('claimed_at__isnull', True), ('superseded_at__isnull', True), _connector='OR'), name='accounts_oauth_one_terminal'), models.CheckConstraint(condition=models.Q(('claimed_at__isnull', True), models.Q(('claimed_at__gte', models.F('created_at')), ('claimed_at__lt', models.F('expires_at'))), _connector='OR'), name='accounts_oauth_claim_in_window'), models.CheckConstraint(condition=models.Q(('superseded_at__isnull', True), ('superseded_at__gte', models.F('created_at')), _connector='OR'), name='accounts_oauth_superseded_after')],
            },
        ),
    ]
