# Generated by Django 5.2.17 on 2026-10-08 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_oauthconnectionattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthconnectionattempt',
            name='encrypted_pkce_verifier',
            field=models.CharField(blank=True, default=None, editable=False, max_length=1024, null=True),
        ),
        migrations.AddConstraint(
            model_name='oauthconnectionattempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('claimed_at__isnull', True), ('encrypted_pkce_verifier__isnull', False), ('superseded_at__isnull', True), models.Q(('encrypted_pkce_verifier', ''), _negated=True)), models.Q(models.Q(('claimed_at__isnull', False), ('superseded_at__isnull', False), _connector='OR'), ('encrypted_pkce_verifier__isnull', True)), _connector='OR'), name='accounts_oauth_pkce_shape'),
        ),
    ]
